FROM python:3.10-alpine
RUN mkdir -p /usr/local/http-server
RUN adduser -D -h /home/runner -s /bin/sh runner
WORKDIR /usr/local/http-server
ADD ./application.py /usr/local/http-server/application.py
RUN chown -R runner:runner /usr/local/http-server/
EXPOSE 8000
USER runner
CMD ["python3", "-u", "/usr/local/http-server/application.py"]